stages:
  - format
  - test

before_script:
  - apt-get update && apt-get install -y cmake

format:
  # 1.67.1
  image: rust@sha256:02a53e734724bef4a58d856c694f826aa9e7ea84353516b76d9a6d241e9da60e
  stage: format
  script:
    - cargo fmt --check

test:
  # 1.67.1
  image: rust@sha256:02a53e734724bef4a58d856c694f826aa9e7ea84353516b76d9a6d241e9da60e
  stage: test
  script:
    - cargo test

build_release:
  # 1.67.1
  image: rust@sha256:02a53e734724bef4a58d856c694f826aa9e7ea84353516b76d9a6d241e9da60e
  script:
    - cargo build --release
  when: manual
  artifacts:
    paths:
      - target/release/modkit

