[package]
name = "mod_kit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "modkit"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
# tried to use noodles, but it wouldn't parse my BAMs (edit. I was using it wrong :<)
# still as of now noodles doesn't have a pileup engine - not a hard requirement, but
# it's certainly nice to have
rust-htslib = "0.40.2"
bio = "1.0.0"
indexmap = "1.9.2"
pulp = "0.10.3"
clap = { version = "4.0.29", features = ["derive"]}
indicatif = { version = "0.17.1", features = ["rayon"] }
itertools = "0.10.5"
anyhow = "1.0.68"
rayon = "1.6.1"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
rand = "0.8.5"

[dev-dependencies]
similar-asserts = "1.4.2"
lazy_static = "1.4.0"
tempfile = "3.3.0"
criterion = "0.4.0"
lazy-regex = "2.3.1"
onig = { version = "6", default-features = false }

# from when I was using a reference sequence
#[[bench]]
#name = "motif_benchmark"
#harness = false
