[package]
name = "mod_kit"
version = "0.1.9"
edition = "2021"

[[bin]]
name = "modkit"
path = "src/bin/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
rust-htslib = "0.43.1"
bio = "1.0.0"
indexmap = "1.9.2"
rustc-hash = "1.1.0"
pulp = "0.10.3"
clap = { version = "4.0.29", features = ["derive", "wrap_help"]}
indicatif = { version = "0.17.1", features = ["rayon"] }
itertools = "0.10.5"
anyhow = "1.0.68"
rayon = "1.6.1"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
rand = "0.8.5"
log = "0.4.0"
log4rs = { version = "1.2.0", features = ["file_appender", "json_encoder"]}
regex = "1.4"
derive-new = "0.5.9"
histo_fp = "0.2.1"
prettytable-rs = "0.10.0"
rust-lapper = "1.1.0"

[dev-dependencies]
similar-asserts = "1.4.2"
