columns:
  - chrom:
      type: str
      description: name of reference sequence from BAM header
  - start_pos:
      type: int
      description: 0-based index of modified base
  - end_pos:
      type: int
      description: start_pos + 1
  - raw_mod_code:
      type: str
      description: single letter code of modified base
  - score:
      type: int
      description: filtered_coverage
  - strand:
      type: str
      description: + for positive strand - for negative strand
  - start_pos:
      type: int
      description: included for compatibility 
  - end_pos:
      type: int
      description: included for compatibility 
  - color:
      type: str
      description: included for compatibility, always 255,0,0
  - filtered_coverage:
      type: int
      description: see definitions
  - percent_modified:
      type: float
      description: N_mod / filtered_coverage
  - N_mod:
      type: int
  - N_canonical:
      type: int
  - N_other_mod:
      type: int
  - N_delete:
      type: int
  - N_filtered:
      type: int
  - N_diff:
      type: int
  - N_nocall:
      type: int
